comdirect:
  browser:
    defaultBrowser: "chromium" # Mögliche Werte: chromium, firefox, webkit
    edgePath: "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"
    autoCloseCookieBanner: true
    headless: true
  ui:
    homeUrl: "https://www.google.com"
    enableJavascriptDebug: true
    enableJavascriptConsole: true
  login:
    url0: "https://kunde.comdirect.de/itx/tfe/starten?execution=e7s1"
    url1: "https://kunde.comdirect.de/itx/tfe/starten?execution=e1s1"
    url2: "https://kunde.comdirect.de/lp/wt/login?execution=e1s1"
    url3: "https://kunde.comdirect.de"
    postUrl: "https://kunde.comdirect.de/lp/wt/login?execution=e1s1&afterTimeout=true#loginAction"
    user: ""
    pin: ""
