name: Release Workflow

on:
  push:
    branches:
      - release

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build project
        run: ./gradlew build

      - name: Determine version
        id: version
        run: |
          version=$(grep 'version=' gradle.properties | cut -d'=' -f2)
          echo "current_version=$version" >> $GITHUB_ENV
          new_version=$(echo $version | awk -F. '{$NF += 1; OFS="."; print $0}' | tr -d ' ')
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Check Git Remote
        run: git remote -v

      - name: Update version in gradle.properties
        run: |
          sed -i "s/version=$current_version/version=$new_version/" gradle.properties
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add gradle.properties
          git commit -m "Bump version to $new_version"
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}
          git push origin release

      - name: Create Git tag
        run: |
          git tag "v${{ env.new_version }}"
          git push origin "v${{ env.new_version }}"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: "v${{ env.new_version }}"
          release_name: "Release v${{ env.new_version }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/libs/your-application.jar
          asset_name: your-application-${{ env.new_version }}.jar
          asset_content_type: application/java-archive
