name: Release Workflow

on:
  push:
    branches:
      - release

jobs:
  build-and-package:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-arm, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            jpackage_type: deb
            javafx_url: https://download2.gluonhq.com/openjfx/23.0.1/openjfx-23.0.1_linux-x64_bin-sdk.zip
          - os: ubuntu-arm
            jpackage_type: deb
            javafx_url: https://download2.gluonhq.com/openjfx/23.0.1/openjfx-23.0.1_linux-aarch64_bin-sdk.zip
          - os: windows-latest
            jpackage_type: exe
            javafx_url: https://download2.gluonhq.com/openjfx/23.0.1/openjfx-23.0.1_windows-x64_bin-sdk.zip
          - os: macos-latest
            jpackage_type: dmg
            javafx_url: https://download2.gluonhq.com/openjfx/23.0.1/openjfx-23.0.1_osx-x64_bin-sdk.zip

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Download JavaFX SDK
        run: |
          echo "Downloading JavaFX SDK from ${{ matrix.javafx_url }}"
          if [ "${{ runner.os }}" == "Windows" ]; then
            curl -L ${{ matrix.javafx_url }} -o javafx-sdk.zip
            powershell -Command "Expand-Archive -Path javafx-sdk.zip -DestinationPath javafx-sdk"
          else
            curl -L ${{ matrix.javafx_url }} -o javafx-sdk.zip
            unzip javafx-sdk.zip -d javafx-sdk
          fi

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build project
        run: ./gradlew shadowJar

      - name: Package with jpackage
        run: |
          jpackage \
            --input build/libs \
            --main-jar comdirect-1.0.0-all.jar \
            --main-class comdirect.Main \
            --name ComdirectApp \
            --type ${{ matrix.jpackage_type }} \
            --module-path javafx-sdk/lib \
            --add-modules javafx.controls,javafx.fxml,javafx.web \
            --icon src/main/resources/icon.ico \
            --app-version ${{ github.run_number }} \
            --dest build/dist

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/dist/ComdirectApp.${{ matrix.jpackage_type }}
          asset_name: ComdirectApp-${{ matrix.os }}.${{ matrix.jpackage_type }}
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
